Require Import Template.monad_utils
        Template.Ast
        (* Template.AstUtils *)
        Template.TemplateMonad
        Template.LiftSubst.
        (* Template.Checker *)
        (* Template.Typing *)
        (* Template.Induction. *)

Require Import Translations.translation_utils.

Require Import Forcing.TemplateForcing
Forcing.translation_utils_bis.


Require Import List.



Import MonadNotation.
Import ListNotations.


Require Import BasicsMisc.
Require Import Hott_lemmas.
Require Import Simple_arithmetic.
Require Import Cubes.
Require Import Monotonicity.
Require Import Cartesian.



(** Check that category laws are definitional *)

Theorem compose_assoc {A B C D : nat}
           (f : A ~> B) (g : B ~> C) (h : C ~> D) :
  h ô (g ô f) = (h ô g) ô f.
Proof.
  reflexivity.
Qed.

(* For compose_id_* it is important that the underlying subset type with the second component in SProp
   was defined as a record with primitive projections *)
Theorem compose_id_right {A B : nat} (f : A ~> B) :
  f ô id = f.
Proof.
  reflexivity.
Qed.

Theorem compose_id_left {A B : nat} (f : A ~> B) :
  id ô f = f.
Proof.
  reflexivity.
Qed.


(** Definition of the forcing machinery *)

Definition 𝐂_obj := nat.
Definition 𝐂_hom := arrow.
Definition 𝐂_id := @id.
Definition 𝐂_comp := @compose.

Quote Definition q_𝐂_obj := nat.
Quote Definition q_𝐂_hom := @arrow.
Quote Definition q_𝐂_id := @id.
Quote Definition q_𝐂_comp := @compose.

Print q_𝐂_obj.

Definition 𝐂 : category :=
  mkCat q_𝐂_obj q_𝐂_hom q_𝐂_id q_𝐂_comp.

Definition Cat : category :=
  makeCatS "𝐂_obj" "arrow" "𝐂_id" "𝐂_comp".

Definition Cat' : category :=
  makeCatS "𝐂_obj" "𝐂_hom" "𝐂_id" "𝐂_comp".

Eval compute in Cat.
Eval compute in 𝐂.
Eval compute in Cat'.



(************ Already defined elsewhere ********)
(*
Definition ForcingTranslation (cat : category) : Translation :=
  {| tsl_id := tsl_ident;
     tsl_tm := f_translate cat;
     tsl_ty := f_translate_type cat;
     tsl_ind := f_translate_ind cat
     (* tsl_context -> kername -> kername -> mutual_inductive_body *)
     (*             -> tsl_result (tsl_table * list mutual_inductive_body) *)
  |}.

Definition add_translation (ctx : tsl_context) (e : global_reference * term): tsl_context :=
  let (Σ, E) := ctx in
  (Σ, e :: E).
*)

(*********** Category changes here *********************)

Instance Cubical : Translation := ForcingTranslation 𝐂.

(*******************************************************)

(* Define a type that, when recursively quoted, imports all we need *)
Definition pack := (arrow , @compose , @id).



Run TemplateProgram (prg <- tmQuoteRec pack ;;
                         tmDefinition "g_ctx" (fst prg)).

Print g_ctx.
Definition ΣE : tsl_context := (Typing.reconstruct_global_context  g_ctx ,[]).




(** Definition of the interval *)

Run TemplateProgram (tImplementTC ΣE "I_TC" "I" Type).
Next Obligation.
  exact (1 ~> p0).
Defined.


Definition initial_map (p : nat) : cube p -> cube 0.
  intro c. intros [a H]. destruct (pos_ge_0 a H).
Defined.



(*
   this proof uses funext to show that any two arrows with initial codomain must be
   equal. If necessary, it is possible to define a version that doesn't use it.
 *)

Definition initial_arrow (p : nat) : 0 ~> p := initial_map p.


Theorem initial_arrow_is_initial (p : nat) (α : 0 ~> p) :
  α = initial_arrow p.
Proof.
  apply funext. intro x. apply funext.
  intros [n H]. easy. 
Qed.

Definition I_end_map (p : nat) (e : bool) : cube p -> cube 1 :=
  (fun (_ : cube p) (_ : finset 1) => e).


Definition I_end (p : nat) (e : bool) : 1 ~> p := I_end_map p e.

Run TemplateProgram (tImplementTC I_TC "I0_TC" "I0" I).
Next Obligation.
  exact (I_end p false).
Defined.

Run TemplateProgram (tImplementTC I0_TC "I1_TC" "I1" I).
Next Obligation.
  exact (I_end p true).
Defined.






(** Imported inductives *)

(* We copy translated definitions of [eq] generated by the OCaml
   forcing plugin, because inducives are not supported yet by the
   template-coq forcing translation *)

Inductive eqᵗ (p : 𝐂_obj) (A : forall p0 : 𝐂_obj, p ~> p0 -> forall p : 𝐂_obj, p0 ~> p -> Type)
(x : forall (p0 : 𝐂_obj) (α : p ~> p0), A p0 α p0 id) :
  (forall (p0 : 𝐂_obj) (α : p ~> p0), A p0 α p0 id) -> Type :=
  eq_reflᵗ : eqᵗ p A x x.


(* This definition will fail if we leave the type of [A] implicit. *)
Definition eq_is_eq :
  forall p (A : forall x : 𝐂_obj, (p ~> x) -> forall x1 : 𝐂_obj, (x ~> x1) -> Type)
         (x y: forall p0 (f:p ~> p0), A p0 f p0 id),
    eq x y -> eqᵗ p A x y. (* it even fails if i don't mention A as an explicit argument
                             here b/c of some mysterious reason *)
Proof.
  intros. rewrite H. apply eq_reflᵗ.
Qed.
 

Run TemplateProgram (TC <- tAddExistingInd I1_TC "Coq.Init.Logic.eq" "eqᵗ" ;;
                          tmDefinition "eq_TC" TC).

Inductive Falseᵗ (p : 𝐂_obj) := .

Run TemplateProgram (TC <- tAddExistingInd eq_TC "Coq.Init.Logic.False" "Falseᵗ" ;;
                        tmDefinition "False_TC" TC).

Inductive orᵗ (p : 𝐂_obj) (A B : forall p0 : 𝐂_obj, p ~> p0 -> forall p1 : 𝐂_obj, p0 ~> p1 -> Prop) : Prop :=
    or_introlᵗ : (forall (p0 : 𝐂_obj) (α : p ~> p0), A p0 α p0 id) -> orᵗ p A B
  | or_introrᵗ : (forall (p0 : 𝐂_obj) (α : p ~> p0), B p0 α p0 id) -> orᵗ p A B.

Run TemplateProgram (TC <- tAddExistingInd False_TC "Coq.Init.Logic.or" "orᵗ" ;;
                        tmDefinition "or_TC" TC).



Inductive andᵗ (p : 𝐂_obj) (A B : forall p0 : 𝐂_obj, p ~> p0 -> forall p1 : 𝐂_obj, p0 ~> p1 -> Prop) : Prop :=
    conjᵗ : (forall (p0 : 𝐂_obj) (α : p ~> p0), A p0 α p0 id) ->
            (forall (p0 : 𝐂_obj) (α : p ~> p0), B p0 α p0 id) -> andᵗ p A B.

Run TemplateProgram (TC <- tAddExistingInd or_TC "Coq.Init.Logic.and" "andᵗ" ;;
                        tmDefinition "and_TC" TC).

Inductive sigTᵗ (p : 𝐂_obj)
          (A : forall p0, p ~> p0 -> forall p, p0 ~> p -> Type)
          (P : forall p0 (α : p ~> p0),
              (forall p (α0 : p0 ~> p), A p (α0 ô α) p id) ->
              forall p, p0 ~> p -> Type) : Type :=
  existTᵗ : forall x : forall p0 (α : p ~> p0), A p0 α p0 id,
    (forall p0 (α : p ~> p0), P p0 α (fun (q : 𝐂_obj) (α0 : p0 ~> q) => x q (α0 ô α)) p0 id) ->
    sigTᵗ p A P.


Run TemplateProgram (TC <- tAddExistingInd and_TC "Coq.Init.Specif.sigT" "sigTᵗ" ;;
                        tmDefinition "sigT_TC" TC).

Inductive unitᵗ (p : 𝐂_obj) :=
  ttᵗ : unitᵗ p.

Run TemplateProgram (TC <- tAddExistingInd sigT_TC "Coq.Init.Datatypes.unit" "unitᵗ" ;;
                        tmDefinition "unit_TC" TC).

Definition complete_TC := unit_TC.






(** Axiom 1 for I : connectedness *)

Definition zero_corner_map (p : nat) : cube 0 -> cube p.
  intros x d. exact false.
Defined.


Definition zero_corner (p : nat) : p ~> 0 := zero_corner_map p .

Definition face_map (p : nat) (b : bool) : S p ~> p := face_c (zero_finset p) b.

Definition degen_map (p : nat) : p ~> S p := degen_c (zero_finset p).

Theorem face_degen (p : nat) (b : bool) : face_map p b ô degen_map p = id.
Proof.
  apply funext.
  intro c. apply funext. intros [[| x] H].
  - compute. assert ((le_S_n 1 p (le_n_S 1 p H)) = H).
    apply Peano_dec.le_unique. rewrite H0. reflexivity.
  - compute. assert ((le_S_n (S (S x)) p (le_n_S (S (S x)) p H)) = H).
    apply Peano_dec.le_unique. rewrite H0. reflexivity.
Qed.

Definition side (p : nat) : cube (S p) -> bool.
  intro c. exact (c (zero_finset p)).
Defined.

Theorem side_face (p q : nat) (b : bool) α (c : cube q) :
  side p ((α ô face_map p b) c) = b.
Proof.
  now compute.
Qed.

Definition homotopy_to_zero (p : nat) (i : forall q : nat, p ~> q -> Iᵗ q q id)
  : forall q : nat, S p ~> q -> Iᵗ q q id.
  intros q α.
  specialize (i q (α ô (degen_map p))).
  pose (side p (α (fun x => false))). destruct b. (* this is a travesty, not natural at all *)
  - exact i.
  - exact (I0ᵗ q).
Defined.

Theorem homotopy_restriction1 (p q : nat) (α : p ~> q) (i : forall q : nat, p ~> q -> Iᵗ q q id)
  : i q α = (homotopy_to_zero p i) q (α ô face_map p true).
Proof.
  unfold homotopy_to_zero.
  rewrite side_face. change (α ô face_map p true ô degen_map p) with (α ô (face_map p true ô degen_map p)).
  rewrite (face_degen p true). reflexivity.
Qed.

Theorem homotopy_restriction2 (p q : nat) (α : p ~> q) (i : forall q : nat, p ~> q -> Iᵗ q q id)
  : I0ᵗ q = (homotopy_to_zero p i) q (α ô face_map p false).
Proof.
  unfold homotopy_to_zero.
  rewrite side_face. reflexivity.
Qed.

Theorem factorization (p : nat) : exists f, zero_corner (S p) = f ô face_map p false.
Proof.
  exists (zero_corner p). apply funext. intro c.
  apply funext. intros [[|x] H].
  - now compute.
  - now compute.
Qed.


Ltac simpl_comp :=
  repeat (match goal with
  | |- context [?α ô ?n] =>
    change (α ô n) with α
  | |- context [?n ô ?α] =>
    change (n ô α) with α
          end).

Ltac simpl_comp_hyp :=
  repeat (match goal with
          | H : context [?a ô ?n] |- _ => change (a ô n) with n in H
          | H : context [?a ô ?n] |- _ => change (a ô n) with a in H
          end).

(* Run TemplateProgram (tmLemma  "tt" (forall (φ : I -> Prop), ((forall i : I, φ i \/ (φ i -> False)) -> (forall i : I, φ i) \/ (forall i : I, φ i -> False)))). *)

Run TemplateProgram (tImplementTC complete_TC "ax1_TC" "ax1"
  (forall (φ : I -> Prop), ((forall i : I, φ i \/ (φ i -> False)) -> (forall i : I, φ i) \/ (forall i : I, φ i -> False)))).
Next Obligation.
  (* STRATEGY OUTLINE *)
  (* we start by applying H0 to decide whether φ(I0) is True or False. then we commit to prove that it is the
   same for every generalized point i. indeed, if φ(i) is different, we are able to build a generalized point
   that extends both I0(0, corner) and i(0, corner) therefore reaching a contradiction. *)
  rename H into H0.
  remember H0 as H1. clear HeqH1.
  specialize (H0 p id (fun p α => I0ᵗ p)). destruct H0.
  - apply or_introlᵗ. intros q α i. simpl_comp.
    (* then apply H1 to the homotopy *)
    pose (homotopy_to_zero q i) as h.
    specialize (H1 (S q) (degen_map q ô α) h). destruct H1.
    + assert ((fun (p2 : nat) (a1 : q ~> p2) => i p2 (a1 ô id)) = (fun (p2 : nat) (α1 : q ~> p2) => (homotopy_to_zero q i) p2 (α1 ô face_map q true))).
      apply funext_dep. intro r. apply funext_dep. intro γ.
      rewrite homotopy_restriction1. reflexivity.  unfold 𝐂_comp. unfold 𝐂_id. unfold 𝐂_obj.
      rewrite H1. clear H1.
      change (homotopy_to_zero q i) with h. simpl_comp. 
      specialize (H0 q (face_map q true)).
      simpl_comp_hyp.
      assert (α = face_map q true ô degen_map q ô α).
      rewrite face_degen. reflexivity.
      rewrite H1. apply H0.
    + specialize (H0 0 (zero_corner (S q))). assert (Falseᵗ 0).
      apply H0. intros q' β.
      pose proof (factorization q) as [γ H1].
      simpl_comp.
      match goal with
      | |- φ _ _ ?t _ _ => assert (t = (fun (p4 : nat) (α3 : q' ~> p4) => I0ᵗ p4))
      end.
      apply funext_dep. intro r. apply funext_dep. intro δ.
      rewrite H1. unfold h.
      rewrite (homotopy_restriction2 q' r δ (fun q0 a => I0ᵗ q0)). reflexivity.
      rewrite H2. clear H2.
      specialize (H q' (β ô zero_corner (S q) ô degen_map q ô α)). apply H.
      inversion H1.
  - apply or_introrᵗ. intros q α i H2.
    pose (homotopy_to_zero q i) as h.
    specialize (H1 (S q) (degen_map q ô α) h). destruct H1.
    + clear H2. unshelve eapply H. exact α. intros q' β.
      specialize (H0 q' (β ô face_map q false)).
       unfold 𝐂_comp in H0. unfold 𝐂_id in H0. unfold 𝐂_obj in H0.
      simpl_comp_hyp.
      change (β ô face_map q false ô (degen_map q ô α)) with (β ô (face_map q false ô degen_map q) ô α) in H0. 
      rewrite face_degen in H0. 
      assert ((fun (p2 : nat) (α1 : q' ~> p2) => h p2 (α1 ô (β ô face_map q false))) = (fun (p2 : nat) (α1 : q' ~> p2) => I0ᵗ p2)).
      apply funext_dep. intro r. apply funext_dep. intro δ. 
      unfold h.
      unshelve erewrite homotopy_restriction2. exact q'. exact δ. exact (fun q0 a => I0ᵗ q0). reflexivity.
      rewrite H1 in H0. exact H0.
    + clear H. apply H0 with (α0 := face_map q true). intros q' β.
      specialize (H2 q' β). simpl_comp_hyp.  unfold 𝐂_comp in H2. unfold 𝐂_id in H2. unfold 𝐂_obj in H2. simpl_comp.
      assert (β ô id ô α = β ô face_map q true ô degen_map q ô α). unshelve erewrite <- face_degen. exact true.  reflexivity. simpl_comp_hyp.
      rewrite H in H2. clear H.  unfold 𝐂_comp. unfold 𝐂_id. unfold 𝐂_obj.
      change (id ô β ô id ô (id ô face_map q true ô id) ô id ô (degen_map q ô α) ô id) with (β ô face_map q true ô degen_map q ô α).
      assert ((fun (p4 : nat) (α3 : q' ~> p4) => h p4 (α3 ô (β ô face_map q true))) = (fun (p3 : nat) (α2 : q' ~> p3) => i p3 (id ô α2 ô β ô id))).
      apply funext_dep. intro r. apply funext_dep. intro δ. simpl_comp.
      change (δ ô (β ô face_map q true)) with (δ ô β ô face_map q true).
      unfold h. rewrite <- homotopy_restriction1. reflexivity. simpl_comp.  rewrite H.
      exact H2.
Defined.



(** Axiom 1 for J *)

(* This should actually be SProp, but we cannot translate SProp as of now.
 So we will need some propositional extensionality i guess *)

Run TemplateProgram (tImplementTC ax1_TC "natp_TC" "natp" (Prop -> Prop)).
Next Obligation.
  rename X into S. rename α into α0.
  exact (forall (p1 : nat) (α1 : p0 ~> p1), S p0 α0 p1 α1 <-> S p1 (α1 ô α0) p1 id).
Defined.


Run TemplateProgram (tImplementTC ax1_TC "nati_TC" "nati" (I -> Prop)).
Next Obligation.
  rename X into i. rename α into α0. 
  exact (forall (p1 : nat) (α1 : p0 ~> p1), α1 ô (i p0 α0) = i p1 (α1 ô α0)).
Defined.

Print natiᵗ_obligation_1.

  


Print Iᵗ_obligation_1.

(* Run TemplateProgram (tImplementTC nati_TC "nati_TC+" "natiTrivial" (forall i : I, nati i)). *)
(* Next Obligation. Print Iᵗ_obligation_1. *)
(*  unfold natiᵗ. unfold natiᵗ_obligation_1. intros. simpl_comp. unfold Iᵗ in i. unfold Iᵗ_obligation_1 in i. *)

    

Arguments existT {_ _} _.

Notation "'Σ' x .. y , P" := (sigT (fun x => .. (sigT (fun y => P)) .. ))
                            (at level 200, x binder, y binder, right associativity).
Notation "( x ; .. ; y ; z )" := (existT x (.. (existT y z) ..)).

Definition J := Σ (i : I), nati i.



Run TemplateProgram (TC1 <- Translate nati_TC "J" ;;
                         tmDefinition "J_TC" TC1).



Run TemplateProgram (tImplementTC J_TC "natj_TC" "natj"
                                  (J -> Prop)).
Next Obligation.
  rename X into j.
  unshelve refine (forall (p1 : nat) (α1 : p ~> p1), j p1 α1 = _).
  specialize (j p id).
  unfold Jᵗ. unshelve refine (existTᵗ _ _ _ _ _).
  - intros. destruct j as [i0 nati0]. (* exact (i0 p2 (α0 ô α1)). *) exact (α0 ô i0 p1 (α1)). (* or other possibility? *)
  - intros. destruct j as [i0 nati0]. unfold natiᵗ. unfold natiᵗ_obligation_1. unfold natiᵗ in nati0. unfold natiᵗ_obligation_1 in nati0.
    intros. simpl_comp.
    (* specialize (nati0 p2 (α0 ô α1) p3 α2). simpl_comp_hyp. exact nati0. *) reflexivity.
Defined.


Check transport.
Lemma dep_eq (A B: Type) (P : A -> Type) (F : forall a : A, P a -> B) {x y : A} {Px : P x} {Py : P y}
      (p : x = y)
      (q : transport P p Px = Py) : F x Px = F y Py.
Proof.
  destruct p. simpl in q. destruct q. reflexivity.
Defined.

(* Run TemplateProgram (tImplementTC natj_TC "natj_all_TC" "natj_all" *)
(*                                   (forall j : J, natj j)). *)
(* Next Obligation. *)
(*   unfold natjᵗ, natjᵗ_obligation_1. *)
(*   intros p1 α1. simpl_comp. *)
(*   remember (j p1 α1) as jp1. *)
(*   destruct jp1. *)
(*   unshelve refine (dep_eq _ _ _ _ _ _). *)
(*   apply funext_dep. intro p2. apply funext_dep. intro α0. *)
(*   remember (j p id) as jp. destruct jp. apply funext. intro x1. *)
(*   unfold natiᵗ, natiᵗ_obligation_1 in *.  *)
  

Run TemplateProgram (tImplementTC natj_TC "mnati_TC" "make_nati"
                                  (I -> J)).
Next Obligation.
  rename X into i. unfold Jᵗ. unshelve eapply existTᵗ.
  - intros p0 α. exact (α ô i p id).
  - intros. unfold natiᵗ. unfold natiᵗ_obligation_1. intros. reflexivity.
Defined.


Run TemplateProgram (tImplementTC mnati_TC "fnati_TC" "forget_nati"
                                  (J -> I)).
Next Obligation.
  specialize (X p id). unfold Jᵗ in X. destruct X. exact (x p id).
Defined.


  


Run TemplateProgram (tImplementTC fnati_TC "eq_nati_TC" "eq_nati"
                                  (forall i : I, forget_nati (make_nati i) = i)).
Next Obligation.
  apply eq_is_eq. apply funext_dep. intro p0. apply funext_dep. intro α.
  unfold forget_natiᵗ. unfold forget_natiᵗ_obligation_1. unfold make_natiᵗ. unfold make_natiᵗ_obligation_1. simpl_comp. reflexivity.
Defined.


Run TemplateProgram (tImplementTC eq_nati_TC "eq2_nati_TC" "eq2_nati"
                                  (forall i : J, make_nati (forget_nati i) = i)).
Next Obligation.
  apply eq_is_eq. apply funext_dep. intro p0. apply funext_dep. intro α.
  unfold forget_natiᵗ. unfold forget_natiᵗ_obligation_1. unfold make_natiᵗ. unfold make_natiᵗ_obligation_1. simpl. simpl_comp.
  destruct (i p0 α).
  unfold natiᵗ in n.  unfold natiᵗ_obligation_1 in n.
  assert ((fun (p1 : nat) (α0 : p0 ~> p1) => α0 ô x p0 id) = x).
  - apply funext_dep. intro p1. apply funext_dep. intro α1. exact (n p0 id p1 α1).
  - revert n. rewrite <- H. intro n. apply f_equal.
    apply funext_dep. intro p1.
    apply funext_dep. intro α0.
    apply funext_dep. intro p2.
    apply funext_dep. intro α1. pose (n p1 α0 p2 α1) as H1.
    simpl_comp_hyp.
    (** True if nati in SProp(?) **)
Admitted.


Run TemplateProgram (tImplementTC eq_nati_TC "proj_nati_TC" "proj_nati"
                                  (forall i : J, natj i -> nati (forget_nati i))).
Next Obligation.
  intro. intro.  unfold forget_natiᵗ. unfold forget_natiᵗ_obligation_1.
   unfold make_natiᵗ. unfold make_natiᵗ_obligation_1. simpl_comp.
  simpl_comp.
  pose (i p id) as H1.
  assert (H1 = i p id). reflexivity.
  change (i p id) with H1. destruct H1.
  pose (i p1 α1) as H2.
  assert (H2 = i p1 α1). reflexivity.
  change (i p1 α1) with H2. destruct H2.
  unfold natiᵗ in n , n0. unfold natiᵗ_obligation_1 in n, n0.
  pose (n p id p1 α1) as Hn0. simpl_comp_hyp. rewrite Hn0.
  
  unfold make_natiᵗ in H, H0. unfold make_natiᵗ_obligation_1.
  unfold forget_natiᵗ. unfold forget_natiᵗ_obligation_1. unfold make_natiᵗ. unfold make_natiᵗ_obligation_1. simpl_comp.
  unfold natjᵗ in H. unfold natjᵗ_obligation_1 in H.
  specialize (H p id p1 α1). simpl_comp_hyp. rewrite H in H1.
  assert (x0 = (fun (p2 : nat) (α0 : p1 ~> p2) => match i p id with
                                          | existTᵗ _ _ _ i0 _ => α0 ô i0 p1 α1
                                          end)).
  exact (TFUtils.ap (fun u : sigTᵗ _ _ _ => match u with
                                         |existTᵗ _ _ _ x _ => x end)  H1).
  rewrite H2. simpl. rewrite <- H0. reflexivity.
Defined.


Axiom funext_dep_refl : forall {A : Type} (P : A -> Type) (f : forall a : A, P a), funext_dep f f (fun x => eq_refl) = eq_refl.

Run TemplateProgram (tImplementTC proj_nati_TC "make_natj_TC" "make_natj"
                                  (forall i : I, nati i -> natj (make_nati i))).
Next Obligation.
  unfold natjᵗ.
  unfold natjᵗ_obligation_1.
  intros.
  unfold make_natiᵗ. unfold make_natiᵗ_obligation_1.
  unfold natiᵗ in H. unfold natiᵗ_obligation_1 in H.
  unshelve refine (dep_eq _ _ _ _ _ _).
  - apply funext_dep. intro p0. apply funext_dep. intro α. simpl_comp.
    specialize (H _ id _ α1). simpl_comp_hyp. rewrite H. reflexivity.
  - simpl. simpl_comp. apply funext_dep. intro x. apply funext_dep. intro.
    apply funext_dep. intro. apply funext_dep. intro. unfold eq_ind_r.
    remember (H p id p1 α1) as H'. simpl_comp_hyp. clear HeqH'.  destruct H'. simpl.
    assert ((funext_dep (fun (p0 : nat) (α : p1 ~> p0) => α ô (α1 ô i p id)) (fun (p2 : nat) (α0 : p1 ~> p2) => α0 ô (α1 ô i p id))
       (fun p0 : nat =>
          funext_dep (fun α : p1 ~> p0 => α ô (α1 ô i p id)) (fun α0 : p1 ~> p0 => α0 ô (α1 ô i p id)) (fun α : p1 ~> p0 => eq_refl))) = eq_refl).
    { assert ((fun p0 : nat => funext_dep (fun α : p1 ~> p0 => α ô (α1 ô i p id)) (fun α0 : p1 ~> p0 => α0 ô (α1 ô i p id)) (fun α : p1 ~> p0 => eq_refl))
              = fun p0 => eq_refl).
      { apply funext_dep. intro. apply funext_dep_refl. }
      rewrite H0. apply funext_dep_refl. }
    rewrite H0. simpl. reflexivity.
Defined.
    
    
   

Run TemplateProgram (tImplementTC make_natj_TC "J0_TC" "J0" J).
Next Obligation.
  unshelve refine (existTᵗ _ _ _ _ _).
  - intros p0 α0. exact (I_end p0 false).
  - intros p0 α0 p1 α1. reflexivity.
Defined.

Run TemplateProgram (tImplementTC J0_TC "J1_TC" "J1" J).
Next Obligation.
  unshelve refine (existTᵗ _ _ _ _ _).
  - intros p0 α0. exact (I_end p0 true).
  - intros p0 α0 p1 α1.  reflexivity.
Defined.

Definition homotopy_to_zero' (p : nat) (i : forall q : nat, p ~> q -> Jᵗ q q id)
  : forall q : nat, S p ~> q -> Jᵗ q q id.
  intros p0 α0. unshelve refine (existTᵗ _ _ _ _ _).
  - intros q α1. pose (α1 ô α0) as α.
    specialize (i p0 (α0 ô (degen_map p))). destruct i as [i Hi].
    intro c. pose (α c) as c'. pose (side p c') as s. destruct s.
    * exact ((i p0 id) (α1 c)).
    * exact (fun _ => false).
  - intros p1 α1 p2 α2. 
    destruct (i p0 (α0 ô degen_map p)) as [i' Hi]. reflexivity.
Defined.

Definition projT1' {p : nat} {A : forall p0 : nat, p ~> p0 -> forall p1 : nat, p0 ~> p1 -> Type}
           {B : forall (p0 : nat) (α : p ~> p0), (forall (p1 : nat) (α0 : p0 ~> p1), A p1 (α0 ô α) p1 id) -> forall p1 : nat, p0 ~> p1 -> Type}
  : sigTᵗ p A B -> forall (p0 : nat) (α : p ~> p0), A p0 α p0 id.
  intros [x y]. exact x.
Defined.

Theorem J_eq {p : nat} (a b : Jᵗ p p id)
  : projT1' a = projT1' b -> a = b.
Proof.
  destruct a. destruct b. simpl.
  intro H. destruct H.
  assert (n = n0). apply proof_irr. rewrite H. reflexivity.
Qed.

Theorem homotopy_restriction1' (p q : nat) (α : p ~> q) (i : forall q : nat, p ~> q -> Jᵗ q q id)
  : i q α = (homotopy_to_zero' p i) q (α ô face_map p true).
Proof.
  assert (projT1' (i q α) = projT1' (homotopy_to_zero' p i q (α ô face_map p true))).
  { apply funext_dep. intro p0. apply funext. intro α0.
    unfold homotopy_to_zero'.
    Opaque side. Opaque degen_c. Opaque face_map. simpl.
    change (α ô face_map p true ô degen_map p) with (α ô (face_map p true ô degen_map p)).
    rewrite face_degen. change (α ô id) with α.
    destruct (i q α) as [j Hj]. simpl.
    apply funext. intro c.
    change (α0 ô (α ô face_map p true)) with ((α0 ô α ô (face_map p true))).
    rewrite side_face.
    specialize (Hj q id). unfold natiᵗ in Hj. unfold natiᵗ_obligation_1 in Hj.
    change (j p0 α0) with (j p0 (α0 ô id ô id ô id)).
    rewrite <- (Hj p0 α0). reflexivity. }
  apply J_eq. exact H.
Defined.



Theorem homotopy_restriction2' (p q : nat) (α : p ~> q) (i : forall q : nat, p ~> q -> Jᵗ q q id)
  : J0ᵗ q = (homotopy_to_zero' p i) q (α ô face_map p false).
Proof.
  assert (projT1' (J0ᵗ q) = projT1' (homotopy_to_zero' p i q (α ô face_map p false))).
  { apply funext_dep. intro p0. apply funext. intro α0.
    unfold homotopy_to_zero'.
    Opaque side. Opaque degen_c. Opaque face_map. simpl.
    change (α ô face_map p false ô degen_map p) with (α ô (face_map p false ô degen_map p)).
    rewrite face_degen. change (α ô id) with α.
    destruct (i q α) as [j Hj].
    apply funext. intro c.
    change (α0 ô (α ô (face_map p false))) with ((α0 ô α ô (face_map p false))).
    rewrite side_face. now compute. }
  apply J_eq. exact H.
Defined.


Run TemplateProgram (tImplementTC J1_TC "ax1'_TC" "ax1'"
  (forall (φ : J -> Prop), ((forall i : J, φ i \/ (φ i -> False)) -> (forall i : J, φ i) \/ (forall i : J, φ i -> False)))).
Next Obligation.
  (* STRATEGY OUTLINE *)
  (* we start by applying H0 to decide whether φ(I0) is True or False. then we commit to prove that it is the
   same for every generalized point i. indeed, if φ(i) is different, we are able to build a generalized point
   that extends both I0(0, corner) and i(0, corner) therefore reaching a contradiction. *)
  rename H into H0.
  remember H0 as H1. clear HeqH1.
  specialize (H0 p id (fun p α => J0ᵗ p)). destruct H0.
  - apply or_introlᵗ. intros q α i.
    (* then apply H1 to the homotopy *)
    pose (homotopy_to_zero' q i) as h.
    specialize (H1 (S q) (degen_map q ô α) h). destruct H1.
    + assert ((fun (p2 : nat) (α1 : q ~> p2) => i p2 (α1 ô id)) = (fun (p2 : nat) (α1 : q ~> p2) => (homotopy_to_zero' q i) p2 (α1 ô face_map q true))).
      apply funext_dep. intro r. apply funext_dep. intro γ.
      rewrite homotopy_restriction1'. reflexivity.
      rewrite H1. clear H1.
      change (homotopy_to_zero' q i) with h. change (id ô id ô (id ô α ô id) ô id ô id) with α.
      specialize (H0 q (face_map q true)).
      change (id ô (id ô face_map q true ô id) ô id ô (degen_map q ô α) ô id ô id) with (face_map q true ô degen_map q ô α) in H0.
      assert (α = face_map q true ô degen_map q ô α).
      rewrite face_degen. reflexivity.
      rewrite H1. apply H0.
    + specialize (H0 0 (zero_corner (S q))). assert (Falseᵗ 0).
      apply H0. intros q' β.
      pose proof (factorization q) as [γ H1]. simpl_comp.
      assert ((fun (p4 : nat) (α3 : q' ~> p4) => h p4 (α3 ô (β ô zero_corner (S q)))) = (fun (p4 : nat) (α3 : q' ~> p4) => J0ᵗ p4)).
      apply funext_dep. intro r. apply funext_dep. intro δ.
      rewrite H1. unfold h. change (δ ô (β ô (γ ô face_map q false))) with ((δ ô β ô γ) ô face_map q false).
      erewrite homotopy_restriction2'. reflexivity.
      rewrite H2. clear H2.
      change (β ô (zero_corner (S q) ô (degen_map q ô α))) with (β ô zero_corner (S q) ô degen_map q ô α).
      specialize (H q' (β ô zero_corner (S q) ô degen_map q ô α)). apply H.
      inversion H1.
  - apply or_introrᵗ. intros q α i H2.
    pose (homotopy_to_zero' q i) as h.
    specialize (H1 (S q) (degen_map q ô α) h). destruct H1.
    + clear H2. eapply H. intros q' β.
      simpl_comp. specialize (H0 q' (β ô face_map q false)). simpl_comp.
      change (id ô (id ô (β ô face_map q false) ô id) ô id ô (degen_map q ô α) ô id) with (β ô (face_map q false ô degen_map q) ô α) in H0.
      simpl_comp_hyp. change (β ô face_map q false ô (degen_map q ô α)) with (β ô (face_map q false ô degen_map q) ô α) in H0.
      rewrite face_degen in H0.
      assert ((fun (p2 : nat) (α1 : q' ~> p2) => h p2 (α1 ô (β ô face_map q false))) = (fun (p2 : nat) (α1 : q' ~> p2) => J0ᵗ p2)).
      apply funext_dep. intro r. apply funext_dep. intro δ. unfold h.
      change (δ ô (β ô face_map q false)) with (δ ô β ô face_map q false).
      erewrite homotopy_restriction2'. reflexivity.
      rewrite H1 in H0. exact H0.
    + clear H. apply H0 with (α0 := face_map q true). intros q' β.
      specialize (H2 q' β). simpl_comp. simpl_comp_hyp.
      change (β ô α) with (β ô id ô α) in H2.
      assert (β ô id ô α = β ô face_map q true ô degen_map q ô α). erewrite <- face_degen. reflexivity.
      rewrite H in H2. clear H.
      change (β ô (face_map q true ô (degen_map q ô α))) with (β ô face_map q true ô degen_map q ô α).
      assert ((fun (p4 : nat) (α3 : q' ~> p4) => h p4 (α3 ô (β ô face_map q true))) = (fun (p3 : nat) (α2 : q' ~> p3) => i p3 (α2 ô β))).
      apply funext_dep. intro r. apply funext_dep. intro δ.
      unfold h.
      change (δ ô (β ô face_map q true)) with (δ ô β ô face_map q true).
      rewrite <- homotopy_restriction1'. reflexivity. rewrite H.
      exact H2.
Defined.





(** Axiom 2 : distinct end points *)

Definition lowest_corner (p : nat) : cube p.
  intro. exact false.
Defined.

Run TemplateProgram (tImplementTC ax1'_TC "ax2_TC" "ax2" (I0 = I1 -> False)).
Next Obligation.
  specialize (H p id). inversion H.
  assert (I0ᵗ p = I1ᵗ p).
  change (I0ᵗ p) with ((fun (p1 : nat) (_ : p ~> p1) => I0ᵗ p1) p id). rewrite H1. reflexivity.
  assert (I_end_map p false = I_end_map p true). 
  change (I_end_map p false) with ((I0ᵗ p)). rewrite H0. reflexivity.
  assert (false = true). 
  change false with (I_end_map p false (lowest_corner p) (zero_finset 0)). rewrite H2. reflexivity.
  inversion H3.
Defined.




(** Connection algebra structure *)

Definition join_arrow {p : nat} (f : 1 + 1 ~> p) : 1 ~> p.
  pose (join_c (zero_finset 0)) as g.
  exact  ( g o f ). 
Defined.

Definition meet_arrow {p : nat} (f : 1 + 1 ~> p) : 1 ~> p.
  pose (meet_c (zero_finset 0)) as g.
  exact ( g o f).
Defined.

Run TemplateProgram (tImplementTC ax2_TC "join_TC" "join_i" (I -> I -> I)).
Next Obligation.
  rename X into i1. rename X0 into i2.
  specialize (i1 p id). specialize (i2 p id).
  pose (fuse_arrows (i1, i2)). exact (join_arrow a).
Defined.

Run TemplateProgram (tImplementTC join_TC "meet_TC" "meet_i" (I -> I -> I)).
Next Obligation.
  rename X into i1. rename X0 into i2.
  specialize (i1 p id). specialize (i2 p id).
  pose (fuse_arrows (i1, i2)). exact (meet_arrow a).
Defined.

Notation "a ⊓ b" := (meet_i a b) (at level 65, left associativity).
Notation "a ⊔ b" := (join_i a b) (at level 65, left associativity).


(** Axiom 3 : computational behaviour of ⊓ *)

Run TemplateProgram (tImplementTC meet_TC "ax3_TC" "ax3"
                                  ( forall i : I, I0 ⊓ i = I0 /\ i ⊓ I0 = I0 /\ I1 ⊓ i = i /\ i ⊓ I1 = i )).
Next Obligation.
  repeat (split; intros).
  - apply eq_is_eq.
    apply funext_dep. intro p1. apply funext_dep. intro α0.
    unfold meet_iᵗ. unfold meet_iᵗ_obligation_1.
    unfold I0ᵗ. unfold I0ᵗ_obligation_1.
    apply funext. intro d. apply funext. intro k. destruct k.
    unfold meet_arrow. simpl. unfold fcompose. simpl. destruct x.
    + reflexivity.
    + easy.
  - apply eq_is_eq.
    apply funext_dep. intro p2. apply funext_dep. intro α1.
    unfold meet_iᵗ. unfold meet_iᵗ_obligation_1.
    unfold I0ᵗ. unfold I0ᵗ_obligation_1.
    apply funext. intro d. apply funext. intro k. destruct k.
    unfold meet_arrow. simpl. unfold fcompose. simpl. destruct x.
    + simpl. unfold I_end. unfold I_end_map.
      apply Bool.andb_false_r.
    + easy.
  - apply eq_is_eq.
    apply funext_dep. intro p3. apply funext_dep. intro α2.
    unfold meet_iᵗ. unfold meet_iᵗ_obligation_1.
    unfold I1ᵗ. unfold I1ᵗ_obligation_1.
    apply funext. intro d. apply funext. intro k. destruct k.
    unfold meet_arrow. simpl. unfold fcompose. simpl. destruct x.
    + simpl. simpl_comp. f_equal. f_equal. unfold lt in l.
      apply Peano_dec.le_unique.
    + easy.
  - apply eq_is_eq.
    apply funext_dep. intro p3. apply funext_dep. intro α2.
    unfold meet_iᵗ. unfold meet_iᵗ_obligation_1.
    unfold I1ᵗ. unfold I1ᵗ_obligation_1.
    apply funext. intro d. apply funext. intro k. destruct k.
    unfold meet_arrow. simpl. unfold fcompose. simpl. destruct x.
    + simpl. simpl_comp. unfold I_end. unfold I_end_map.
      rewrite Bool.andb_true_r. repeat f_equal. apply Peano_dec.le_unique.
    + easy.
Defined.





(** Axiom 4 : computational behaviour of ⊔ *)

Run TemplateProgram (tImplementTC ax3_TC "ax4_1_TC" "ax4_1" (forall i : I, I0 ⊔ i = i)).
Next Obligation.
  unfold join_iᵗ. unfold join_iᵗ_obligation_1. 
  assert ((fun (p0 : nat) (α : p ~> p0) => join_arrow (fuse_arrows (I0ᵗ p0, i p0 (id ô (α ô (id ô id) ô id))))) =  (fun (p0 : nat) (α : p ~> p0) => i p0 (α ô (id ô id) ô id))).
  apply funext_dep. intro q. apply funext_dep. intro α.
  apply funext. intro c.
  apply funext. intros [x px].
  destruct x.
  - simpl_comp.
    replace (join_arrow (fuse_arrows (I0ᵗ q, i q α))) with (join_c (zero_finset 0) o (fuse_arrows (I0ᵗ q, i q α))).
    + Transparent fuse_cube_maps. compute.
      match goal with
      | [ |- _ _ (exist _ 0 ?XX) = _ _ (exist _ 0 px) ] => erewrite (Peano_dec.le_unique _ _ XX px)
      end. reflexivity.
    + unfold join_arrow. reflexivity.
  - assert False. easy. inversion H.
  - rewrite H. apply eq_reflᵗ.
Defined.




Run TemplateProgram (tImplementTC ax4_1_TC "ax4_TC" "ax4"
                                  (forall i : I, I0 ⊔ i = i /\ i ⊔ I0 = i /\ I1 ⊔ i = I1 /\ i ⊔ I1 = I1)).
Next Obligation.
  repeat (split; intros); apply eq_is_eq.
  - apply funext_dep. intro p1. apply funext_dep. intro α0.
    unfold join_iᵗ. unfold join_iᵗ_obligation_1.
    unfold I0ᵗ. unfold I0ᵗ_obligation_1.
    apply funext. intro d. apply funext. intro k. destruct k.
    unfold join_arrow. simpl. unfold fcompose. simpl. destruct x.
    + unfold  le_lt_dec.
      simpl. repeat f_equal. apply Peano_dec.le_unique.
    + easy.
  - apply funext_dep. intro p2. apply funext_dep. intro α1.
    unfold join_iᵗ. unfold join_iᵗ_obligation_1.
    unfold I0ᵗ. unfold I0ᵗ_obligation_1.
    apply funext. intro d. apply funext. intro k. destruct k.
    unfold join_arrow. simpl. unfold fcompose. simpl. destruct x.
    + unfold le_lt_dec. simpl. 
      unfold I_end. unfold I_end_map.
      rewrite Bool.orb_false_r.
      repeat f_equal. apply Peano_dec.le_unique.
    + easy.
  - apply funext_dep. intro p3. apply funext_dep. intro α2.
    unfold join_iᵗ. unfold join_iᵗ_obligation_1.
    unfold I1ᵗ. unfold I1ᵗ_obligation_1.
    apply funext. intro d. apply funext. intro k. destruct k.
    unfold join_arrow. simpl. unfold fcompose. simpl. destruct x.
    + unfold le_lt_dec. simpl. reflexivity.
    + easy.
  - apply funext_dep. intro p3. apply funext_dep. intro α2.
    unfold join_iᵗ. unfold join_iᵗ_obligation_1.
    unfold I1ᵗ. unfold I1ᵗ_obligation_1.
    apply funext. intro d. apply funext. intro k. destruct k.
    unfold join_arrow. simpl. unfold fcompose. simpl. destruct x.
    + simpl. unfold I_end. unfold I_end_map.
      rewrite Bool.orb_true_r. reflexivity.
    + easy.
Defined.
    